services:
  dataBase2: 
    image: postgres:latest
    container_name: db2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  volumes:
      - ./scripts/newDB.sql:/docker-entrypoint-initdb.d/init.sql